exports.LANGUAGES_LOAD_REQUEST = 'LANGUAGES_LOAD_REQUEST'
exports.LANGUAGES_LOAD_SUCCESS = 'LANGUAGES_LOAD_SUCCESS'
exports.LANGUAGES_LOAD_FAILURE = 'LANGUAGES_LOAD_FAILURE'

exports.LANGUAGES_DOWNLOAD_REQUEST = 'LANGUAGES_DOWNLOAD_REQUEST'
exports.LANGUAGES_DOWNLOAD_SUCCESS = 'LANGUAGES_DOWNLOAD_SUCCESS'
exports.LANGUAGES_DOWNLOAD_FAILURE = 'LANGUAGES_DOWNLOAD_FAILURE'

exports.ALPHABET_LOAD_REQUEST = 'ALPHABET_LOAD_REQUEST'
exports.ALPHABET_LOAD_SUCCESS = 'ALPHABET_LOAD_SUCCESS'
exports.ALPHABET_LOAD_FAILURE = 'ALPHABET_LOAD_FAILURE'

exports.ALPHABET_DOWNLOAD_REQUEST = 'ALPHABET_DOWNLOAD_REQUEST'
exports.ALPHABET_DOWNLOAD_SUCCESS = 'ALPHABET_DOWNLOAD_SUCCESS'
exports.ALPHABET_DOWNLOAD_FAILURE = 'ALPHABET_DOWNLOAD_FAILURE'

exports.LOAD_STATE_REQUEST = 'LOAD_STATE_REQUEST'
exports.LOAD_STATE_SUCCESS = 'LOAD_STATE_SUCCESS'

exports.QUIZ_START = 'QUIZ_START'
exports.QUIZ_NEXT = 'QUIZ_NEXT'

exports.PRONOUNCATION_LOAD_SUCCESS = 'PRONOUNCATION_LOAD_SUCCESS'
