exports.QUIZ_START_REQUEST = 'QUIZ_START_REQUEST'
exports.QUIZ_START_SUCCESS = 'QUIZ_START_SUCCESS'
exports.QUIZ_START_FAILURE = 'QUIZ_START_FAILURE'

exports.QUIZ_NEXT = 'QUIZ_NEXT'

exports.ALPHABET_SELECT = 'ALPHABET_SELECT'

exports.ALPHABET_LOAD_REQUEST = 'ALPHABET_LOAD_REQUEST'
exports.ALPHABET_LOAD_SUCCESS = 'ALPHABET_LOAD_SUCCESS'
exports.ALPHABET_LOAD_FAILURE = 'ALPHABET_LOAD_FAILURE'

exports.ALPHABET_LOAD_AUDIO_REQUEST = 'ALPHABET_LOAD_AUDIO_REQUEST'
exports.ALPHABET_LOAD_AUDIO_SUCCESS = 'ALPHABET_LOAD_AUDIO_SUCCESS'
exports.ALPHABET_LOAD_AUDIO_FAILURE = 'ALPHABET_LOAD_AUDIO_FAILURE'

exports.ALPHABET_DOWNLOAD_REQUEST = 'ALPHABET_DOWNLOAD_REQUEST'
exports.ALPHABET_DOWNLOAD_SUCCESS = 'ALPHABET_DOWNLOAD_SUCCESS'
exports.ALPHABET_DOWNLOAD_FAILURE = 'ALPHABET_DOWNLOAD_FAILURE'
exports.ALPHABET_DOWNLOAD_PROGRESS = 'ALPHABET_DOWNLOAD_PROGRESS'

exports.ALPHABETS_READ_REQUEST = 'ALPHABETS_READ_REQUEST'
exports.ALPHABETS_READ_SUCCESS = 'ALPHABETS_READ_SUCCESS'
exports.ALPHABETS_READ_FAILURE = 'ALPHABETS_READ_FAILURE'

exports.ALPHABETS_SAVE_REQUEST = 'ALPHABETS_SAVE_REQUEST'
exports.ALPHABETS_SAVE_SUCCESS = 'ALPHABETS_SAVE_SUCCESS'
exports.ALPHABETS_SAVE_FAILURE = 'ALPHABETS_SAVE_FAILURE'

exports.ALPHABETS_DOWNLOAD_REQUEST = 'ALPHABETS_DOWNLOAD_REQUEST'
exports.ALPHABETS_DOWNLOAD_SUCCESS = 'ALPHABETS_DOWNLOAD_SUCCESS'
exports.ALPHABETS_DOWNLOAD_FAILURE = 'ALPHABETS_DOWNLOAD_FAILURE'

exports.ALPHABETS_REMEMBER_SELECTED_REQUEST = 'ALPHABETS_REMEMBER_SELECTED_REQUEST'
exports.ALPHABETS_REMEMBER_SELECTED_SUCCESS = 'ALPHABETS_REMEMBER_SELECTED_SUCCESS'
exports.ALPHABETS_REMEMBER_SELECTED_FAILURE = 'ALPHABETS_REMEMBER_SELECTED_FAILURE'
